New Python Notebook doing a deeper dive into COG Overview Resampling
cloudnativegeo/cloud-optimized-geospatial-formats-guide pull request #95
Opened 2023-11-15 16:58 UTC by wildintellect

Content was already checked by @kylebarron 
- [ ] Verify site builds correctly (including TOC links etc)

2023-11-15 17:42 UTC, kylebarron commented
I usually use squash merge everywhere 🤷‍♂️

2023-12-20 20:42 UTC, zacharyDez requested changes
The notebooks are great! I made some changes in #98 mostly around the text blocks. When we merge that, I'll add my ✅ .

2024-01-03 22:47 UTC, kylebarron approved these changes

2024-01-03 22:47 UTC, kylebarron commented on cloud-optimized-geotiffs/cogs-examples.ipynb
> +    "Note: The whole point is that we _don't_ download data. So, in future examples, we will demonstrate how to access just subsets of data using COG and compare that with a GeoTIFF."
```suggestion
    "Note: The whole point of the "cloud-optimized" part of Cloud-Optimized GeoTIFF is that we _don't_ download the entire file. So, in future examples, we will demonstrate how to access just subsets of data using COG and compare that with a GeoTIFF."
```

2024-01-04 13:26 UTC, zacharyDez approved these changes

2024-01-04 16:18 UTC, merged